### ISSUE TITLE
GPS coordinates precision is only 3 digits when it's 8 in input file

### ISSUE THREAD

**Issue by gromain** [zsiki/Find-GCP#12]
Hey,

I saw a small issue where the GPS coordinates are rounded to 3 digits, even when the input file is actually 8 digits long. Of course this creates issues depending on the geoid and projections used. In my case, this causes a huge loss in precision (about 40m at my location).

Is there a reason for this?

I would vote for reusing directly the data given in the GCP input file, so the user determines the final precision. I feel there is no use[ to transform to a float](https://github.com/zsiki/Find-GCP/blame/master/gcp_find.py#L130) to then [export it as a string](https://github.com/zsiki/Find-GCP/blame/master/gcp_find.py#L234). Moreover, this makes the system more robust and future proof, as there will be no need to add more digits when the tools become more precise (for example, with RTK GPS, you're looking at a 10-100mm accuracy, much much more than with a standard GPS receiver).

I can write a PR for this.

**Comment by zsiki** [comment]
You are right. I mostly use projected coordinates in meters. I'll store coordinates as strings and no precision will be lost.

**Comment by gromain** [comment]
Exactly the commit I made on my machine to continue my tests :-)

**Comment by gromain** [comment]
Thanks a lot!
