### ISSUE TITLE
GCP input file format

### ISSUE THREAD

**Issue by lucadelu** [zsiki/Find-GCP#14]
Could I suggest to use the CSV format with the same format of [GCPEditorPro](https://github.com/uav4geo/GCPEditorPro)?

Examples

[gps-template-latlon.csv](https://github.com/zsiki/Find-GCP/files/8332004/gps-template-latlon.csv)
[gps-template-m.csv](https://github.com/zsiki/Find-GCP/files/8332005/gps-template-m.csv)

**Comment by zsiki** [comment]
Sure. I'll add a command line switch --nez to mark northing,easting, elevation order in CGP input file. This way compatibility won't be broken to older versions users.
