### ISSUE TITLE
exif_pos.py 

### ISSUE THREAD

**Issue by ZohaibDurrani** [zsiki/Find-GCP#15]
Hello, faced some issues in exif_pos.py. When I tried to print the "GPSInfo" it only printing the integer instead of whole json format of "GPSInfo".   Moreover, I made little changes in code and now working fine.

Here are some issues which I faced. 
![Screenshot (88)](https://user-images.githubusercontent.com/79791177/162285506-e2715ad5-0def-4863-9416-60da5946a6ee.png)

**Here I tried with other PIL version but have faced issues.**
![Screenshot (89)](https://user-images.githubusercontent.com/79791177/162285529-9b09c016-efab-4141-9fdd-05e7590f0fab.png)

**Comment by zsiki** [comment]
The error handling was not perfect in ```exif_pos```. If the image has no EXIF or GPSInfo tag it failed with a Python error.
I use PIL version 9.0.1.
Please send me your PIL version, run the following command to get it:

```
python3 -c "import PIL;print(PIL.__version__)"
```
Why didn't you send your correction in the code? Next time please send me the image causes the error to help me to find the bug.

I try to improve the error handling in the program, but something has been changed also in PIL (pillow) in ```getexif``` function. I'll debug the code soon.

**Comment by zsiki** [comment]
I tested the code with PIL version 9, but is should work with older versions, too.

**Comment by ZohaibDurrani** [comment]
Sir I am now using PIL version 5.2. I also tested exif_pos.py with PIL version 8 and 9.0.0 but didn't worked for me. Here is the changes which I made. 
[exif_pos.zip](https://github.com/zsiki/Find-GCP/files/8455244/exif_pos.zip)

**Comment by zsiki** [comment]
I can't see any significant change in your code, you have simplified the code to handle a single image. Please send me the image which the program fails with and the error message you got.
Here is the output of *exif_pos* for your images:

```
./exif_pos.py Zohaib/*.JPG
Zohaib/160233726-f40e31b5-7639-4171-a53c-f81e018f28cc.JPG,67.225248,30.460289,1870.52,2022:03:23 11:37:17
Zohaib/160233926-2cf2bfb9-1a2d-40da-b77e-2da72b440122.JPG,67.225343,30.457131,1880.59,2022:03:23 11:21:49
Zohaib/160233995-b81c1b55-b5c0-4aff-81f7-27fa51551c4b.JPG,67.225036,30.460114,1910.37,2022:03:23 10:13:27
```
If the latest code of exif_pos.py doesn't produce the same output with PIL version 9, then the error is on your side.

I also tested the sample JPG images with PIL version 7:
```
./exif_pos.py samples/DJI*.JPG
samples/DJI_0172.JPG,19.054540,47.481730,132.43,2020:08:26 15:19:07
samples/DJI_0173.JPG,19.054538,47.481727,132.53,2020:08:26 15:19:09
samples/DJI_0174.JPG,19.054595,47.481717,132.63,2020:08:26 15:19:25
```
Do you know that you should install pillow packages to have the latest PIL version. Please upgrade your PIL using the following command:
```
pip install pillow --upgrade
```
