### ISSUE TITLE
[Question] What material did you use?

### ISSUE THREAD

**Issue by lupionpe** [zsiki/Find-GCP#22]
Hello, I have been using this project a lot in the last couple months.

I have made 10 arucos 4x4 of 1m each and they work most of the time.

One issue that I am having is that I made the arucos in black/white by printing on a tarp.
![PXL_20231006_204147326](https://github.com/zsiki/Find-GCP/assets/65565211/59a39068-0781-4b85-872b-d4d4e39bd9ff)

What happens is that the tarp is somewhat reflective, and in sunny days the arucos are harder to be identified in the photos.

Did you get this issues?
Is there a way to overcome in the software or in the aruco making?

cc: @felupion

**Comment by zsiki** [comment]
I'm happy you use Find-GCP :)

You had better to use gray background and non-reflective material in sunshine.

https://raw.githubusercontent.com/zsiki/Find-GCP/master/samples/grey_black.png

The best solution was for us to use gray plastic sheet, and the black part of the ArUco marker was added as black non-reflective self-adhesive film (this is used mostly by graphics designers on exhibitions).
