### ISSUE TITLE
Coordinate precision too low

### ISSUE THREAD

**Issue by CodingGhost** [zsiki/Find-GCP#23]
I noticed that the output coordinates are truncated to 3 decimal places in the output file, why is that? this would correspond to about 111 meters of accuracy which obviously is way too high. I changed it to 8 decimal places for about millimeter accuracy and that seems to work. Is there any reason for this limit?

**Comment by zsiki** [comment]
I used gcp_find.py with projected coordinates (e.g. UTM) so far. You are right, for geographical coordinates (longitude, latitude) three decimals are not enough, but 8 decimals seem me nonsense for projected coordinates.
The solution is to use the same number of decimals in the output as in the input.

**Comment by CodingGhost** [comment]
I have 8 decimal places as input, but yes using same as input is the best way!
