### ISSUE TITLE
Issues with false positive using 3x3

### ISSUE THREAD

**Issue by lupionpe** [zsiki/Find-GCP#25]
Hello,

I am trying to use the 3x3 in my projects instead of 4x4, in order to fly higher and still get the detection.

I have also been experimenting with different materials, so I can also get detection on sunny days.

In this case, I am using a printed tarp using 4x4 and a cotton mesh with 3x3.

The problem I am facing is when I run the 3x3 detection, I do not find the aruco 3x3, but I find a lot of false positives.

I ran the code on the last version of [zsiki/Find-GCP: Find ArUco markers in digital photos](https://github.com/zsiki/Find-GCP) using **Python 3.11.6** and **opencv-python         4.8.0.76**

```sh
python3 gcp_find.py -d 99 --debug /Users/lupion/Downloads/100MEDIA\ 2/*.JPG
```

### Exemple detecting 4x4 instead of 3x3
<img width="817" alt="image" src="https://github.com/zsiki/Find-GCP/assets/65565211/12f71465-1c57-48ef-9e78-1c551d716e14">

### Exemple of a lot of false positives
<img width="902" alt="image" src="https://github.com/zsiki/Find-GCP/assets/65565211/d6446a69-1496-45d8-953f-b4f527acfda2">

### Original images:

![DJI_0003](https://github.com/zsiki/Find-GCP/assets/65565211/d07c71e7-4ec0-4ef7-847b-e57a319724ef)

![DJI_0047](https://github.com/zsiki/Find-GCP/assets/65565211/0fdfb4e6-4fb4-4827-8b8a-421c0737dd02)

Am I doing something wrong here?

Cheers
Lupion

**Comment by zsiki** [comment]
Dear Lupion,

Your 3x3 marker on the first photo is mirrored. Try my image:
![test1a](https://github.com/zsiki/Find-GCP/assets/1023856/04bd6dcf-1e53-4db3-9a6c-27bf2942fc9d)
I found similar error with 4x4 markers, you may try to change errorCorrectionRate.

The chance to find false match is increased by reducing the marker grid to 3x3. You have to use gcp_check.py. It is strange, I got different false matches on your image:
![image](https://github.com/zsiki/Find-GCP/assets/1023856/b0836da1-8b48-4956-b869-4c9dc848ac81)

Zoltan
